### ISSUE TITLE
Problem Running on Mac

### ISSUE THREAD

**Issue by rogiedodgie** [pboutinaud/SHIVA_PVS#1]
Hi all,
I am trying to get this to run, just using the CPU, on my iMac (Monterey 12.1), 3.6Ghz 8-core, 2019)
I am working with Python 3.7, tensorflow2.7, nibabel confirmed as installed. 
I changed the gpu flag to -1 in the run_predict_one_file.sh  file.
However, I can't seem to get past this error.
Any suggestions would be much appreciated!
Best,
Roger

---------------------------------------------------------------------------------------------------------------------------
WARNING:tensorflow:Mixed precision compatibility check (mixed_float16): WARNING
The dtype policy mixed_float16 may run slowly because this machine does not have a GPU. Only Nvidia GPUs with compute capability of at least 7.0 run quickly with mixed_float16.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
2022-08-09 09:15:58.720410: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO : Predicting fold : 20211030-162753_Unet3Dv2-10.7.2-1.8-T1.VRS_fold_1x6_pi_fold_0_model
Traceback (most recent call last):
  File "./predict_one_file.py", line 127, in <module>
    batch_size=1
  File "/Users/rorden/Desktop/EVPSauto/env/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/rorden/Desktop/EVPSauto/env/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxPool3D' used by {{node model/Enc_Max_D7/MaxPool3D}} with these attrs: [ksize=[1, 2, 2, 2, 1], padding="VALID", T=DT_HALF, data_format="NDHWC", strides=[1, 2, 2, 2, 1]]
Registered devices: [CPU]
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_BFLOAT16, DT_HALF]
  device='CPU'; T in [DT_FLOAT]

	 [[model/Enc_Max_D7/MaxPool3D]] [Op:__inference_predict_function_4139]

**Comment by pboutinaud** [comment]
Hi Roger,
I am aware of the problem, it seems that the MaxPool3D layer is not correctly implemented for the CPU version of tensorflow 2.7, I couldn't find an easy way to fix that and I am currently waiting for tensorflow to fix that problem in a future version.
A way to solve that problem would be to train the model by replacing the MaxPool3D layer by a strided 3D convolution, it works with the same performances but add a lot of parameters to the model and is longer to train, then we decided not to waste electricity on that approach.
As noted in the requirements, a GPU is needed to run the inferences.
Sorry for the inconvenience.
Best regards 
Philippe

**Comment by rogiedodgie** [comment]
Hi Philippe,
Thank you for the response!
We have multiple NVIDIA capable desktops so I will try to run the GPU
version.
Your program is particularly attractive to us as we have a large dataset
with T1 and Flair, but not T2!
Best.
Roger

**Comment by rogiedodgie** [comment]
Hi Philippe,
I have managed to get it to run, partially, but it seems that only the
first two models are used, there are exceptions loading models 3-5. A
Any advice?
Best,
Roger

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is
often sufficient.
1/1 [==============================] - 3s 3s/step
INFO : Predicting fold :
20211030-162753_Unet3Dv2-10.7.2-1.8-T1.VRS_fold_1x6_pi_fold_1_model
2022-08-10 19:56:16.459017: I
tensorflow/core/grappler/optimizers/generic_layout_optimizer.cc:353] Cancel
Transpose nodes around Pad:
transpose_before=model/Dec_Ups_D2/concat_2-0-0-TransposeNCDHWToNDHWC-LayoutOptimizer
pad=model/Dec_ZPad_D2/Pad
transpose_after=model/Dec_Unet_D2/concat-0-TransposeNDHWCToNCDHW-LayoutOptimizer
2022-08-10 19:56:16.459109: I
tensorflow/core/grappler/optimizers/generic_layout_optimizer.cc:353] Cancel
Transpose nodes around Pad:
transpose_before=model/Dec_Ups_D3/concat_2-0-0-TransposeNCDHWToNDHWC-LayoutOptimizer
pad=model/Dec_ZPad_D3/Pad
transpose_after=model/Dec_Unet_D3/concat-0-TransposeNDHWCToNCDHW-LayoutOptimizer
1/1 [==============================] - 1s 741ms/step
INFO : Predicting fold :
20211030-162753_Unet3Dv2-10.7.2-1.8-T1.VRS_fold_1x6_pi_fold_2_model
2022-08-10 19:56:18.407418: I
tensorflow/core/grappler/optimizers/generic_layout_optimizer.cc:353] Cancel
Transpose nodes around Pad:
transpose_before=model/Dec_Ups_D2/concat_2-0-0-TransposeNCDHWToNDHWC-LayoutOptimizer
pad=model/Dec_ZPad_D2/Pad
transpose_after=model/Dec_Unet_D2/concat-0-TransposeNDHWCToNCDHW-LayoutOptimizer
2022-08-10 19:56:18.407497: I
tensorflow/core/grappler/optimizers/generic_layout_optimizer.cc:353] Cancel
Transpose nodes around Pad:
transpose_before=model/Dec_Ups_D3/concat_2-0-0-TransposeNCDHWToNDHWC-LayoutOptimizer
pad=model/Dec_ZPad_D3/Pad
transpose_after=model/Dec_Unet_D3/concat-0-TransposeNDHWCToNCDHW-LayoutOptimizer
1/1 [==============================] - 1s 738ms/step

WARNING : Exception loading model : {predictor_file}
{err}

WARNING : Exception loading model : {predictor_file}
{err}

WARNING : Exception loading model : {predictor_file}
{err}
Inference time : {chrono1} sec.

INFO : Done with predictions -> {output_path}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib

**Comment by pboutinaud** [comment]
Hello Roger,
This may be a GPU memory problem.
Please try to run the inferences with only one of the model that cause the problem, for instance only with the third one. If the inference is ok, then there is a memory problem ; tensorflow has data leaks and sometimes running consecutively several models in the same process causes crashes. You could also try to reduce the  batch size.
The 5 TF models are generated from a training dataset stratified in 5 folds, each of the model comes from training with one fold. If you can generate segmentations from each model in separate processes and then average the 5 segmentations from each model, then you’ll have the same results as I have.
If this does not work, maybe you can send me one of your nifti files and I’ll try to run it from my side.
However I am on vacations till August 22th, and I won’t be able to try anything until then.
I am also interested in any result you may have with these models.
Best regards
Philippe

**Comment by rogiedodgie** [comment]
I hope you enjoy your vacation as well!
Roger

**Comment by rogiedodgie** [comment]
Hi Philippe!
I thought of that, and changed the order of the estimations in the
run_predict_one_file.sh file.
If I estimate models 3,4 and 5 first, they all fail, but models 0,1 and 2
still run!
Even just running models individually, it seems that neither 3, nor 4 nor 5
work.
Which makes me think that models 3-5 are corrupt, or else they are models
that somehow do require more space, even when run alone.
I am actually running the attached nifti file.
  --> test_T1_Axial_resampled_111_cropped_intensity_normed.nii.gz
https://drive.google.com/file/d/1KvMyebB1FcLOUMwi-XSPvpbRPv9KMnvE/view?usp=sharing

Just to test and see if I can get this working.
We would be very interested in working with you as well, we have lots of
healthy data and stroke data and are interested in PVS.
Best,
Roger

**Comment by pboutinaud** [comment]
Hello Roger,
I have done some tests with a fresh computer / environment :
 - I used a Windows 11 PC with a NVIDIA 1080 Ti GPU.
 - installed a new conda environment  with python 3.7, tensorflow 2.9.1 came with it. There's a yml environement file in the zip file below describing the dependencies, it can be used to create a new environment.
 - downloaded the TF model files from our server for the T1 -> PVS segmentation (both v0 and v1)
 - modified a bit the predict_one_file.py to more easily test the models (the code is in the zip file)
 - looked at your nifti file : the intensity of the voxels were not normalized between 0 and 1 then I used a simple minmax transformation (see the code in the zip file). In the readme it's said that we used the 99th percentile as the max but I didn't see any hotspot in your image than it should be ok. However the image is a bit blurry, maybe an interpolation artefact ?

I didn't get any problem loading any model and to use them for inference. Could you try it from your side with a minmax normalised image ?
Without the minmax normalisation, the segmentation produced an image filled with NaN (neural networks like numbers around 0).

It seems that a higher threshold than 0.5 should be used and/or filter out the small clusters, since I think that the inference picks a lot of noise in your image.

I also added some code in predict_one_file.py (see zip file) to create the result in a format that can used by 3D Slicer as a segmentation input (segmentation also in the zip file). 

[sent.zip](https://github.com/pboutinaud/SHIVA_PVS/files/9395509/sent.zip)

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/107562757/185956935-c7d670d6-8408-43e2-98bf-ef25dc75735b.png">

**Comment by rogiedodgie** [comment]
Aha, welcome back from vacation Philippe!
Thank you for taking a look at this.
I will do the min/max normalize and see if that works as per your
instructions.
I will let you know how it goes, thank you so much.
I hope I can get some results that are paperworthy for us!
Best,
Roger

**Comment by rogiedodgie** [comment]
Philippe!
I got everything to work using the same setup you have.
I now have tons of data to look at.
I already have one postdoc using the data.
Maybe it would be useful at this point to meet with you to discuss the data
and see if you would like to collaborate on potential papers?
LMK and hope all is well.
Best,
Roger

**Comment by rogiedodgie** [comment]
Hi Philippe,
Can you tell me if the output files from SHIVA_PVS are in native space or
MNI space?
Thanks!
Roger

**Comment by pboutinaud** [comment]
Hello Roger,
The tensorflow model does not care about the reference space, it takes a numpy array as input and create a numpy array as output. It's when you save the numpy array that you have to be careful to save it with the correct transformation ; for instance when using nibabel to create nifti files, as illustrated in the python code, you read the input image, uou have to get the affine transoformation and to use it when creating the output nifti file.
What kind of problem do you have ?

It would be interesting to collaborate as you suggested, I'll send you a email to initiate this discussion later.

Regards,
Philippe

**Comment by rogiedodgie** [comment]
Mainly, I am having issues getting the results into normalized space.
And also not sure how best to quantify the results (i.e. total voxels in
the semiovale or BG, vs total clusters).
With some assistance, I think we have a chance at a quick paper in stroke
with our dataset if healthy hemisphere EPVS is related in any way to stroke
or behavior!
Best,
Roger
